version: '3'

services:
  golang-service:
    build:
      context: .
      dockerfile: Dockerfile_server
    ports:
      - "8080:8080"

  angular-service:
    build:
      context: .
      dockerfile: Dockerfile_client
    ports:
      - "4200:443"
