FROM node:lts AS build

COPY my-app/ /my-app
COPY cert/ /cert

WORKDIR /my-app

RUN npm install -g @angular/cli
RUN npm install

EXPOSE 4200

RUN ng build

CMD ["ng", "serve", "--host", "0.0.0.0", "--ssl", "true", "--ssl-key", "../cert/server.key", "--ssl-cert", "../cert/server.crt"]
