FROM node:lts-alpine AS builder

COPY my-app/ /my-app
COPY cert/ /cert

WORKDIR /my-app

RUN npm install -g @angular/cli && \
    npm install && \
    npm run build

FROM nginx:alpine

COPY --from=builder /my-app/dist/my-app/browser /usr/share/nginx/html

COPY /my-app/nginx.conf /etc/nginx/conf.d/default.conf

COPY /cert/server.key /etc/nginx/ssl/server.key
COPY /cert/server.crt /etc/nginx/ssl/server.crt

EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
